sellsei_ecommerce_core:
    resource: "@SellseiEcommerceCoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
